language: python
python:
- "2.7"
install:
- sudo apt-get update
- sudo apt-get install build-essential python-dev libigraph0-dev
- pip install numpy nose==1.0.0
- python setup.py develop
- python -c "import nltk; nltk.download('stopwords')"
script:
- nosetests
